import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarApp from '@/components/NavbarApp'
import SessionProviderClientComponent from './AuthProvider'
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" className={"bg-ghost-white " + inter.className}>
      <body className="bg-ghost-white min-h-80">
        <SessionProviderClientComponent session={session}>
          <div className="max-w-5xl mx-auto p-2">
            <NavbarApp />
            <div className="mt-4 max-w-*">{children}</div>
          </div>
        </SessionProviderClientComponent>
      </body>
    </html >
  );
}
