import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarApp from '@/components/NavbarApp'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"bg-ghost-white " + inter.className}>
      <body className="bg-ghost-white min-h-100 ">
        <div className="max-w-4xl mx-auto p-4">
          <NavbarApp />
          <div className="mt-4 max-w-*">{children}</div>
        </div>
      </body>
    </html >
  );
}
