import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarApp from '@/components/NavbarApp'
import SessionWrapper from "@/components/SessionWrapper"
import { AuthProvider } from "./Providers"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en" className={"bg-ghost-white " + inter.className}>
        <body className="bg-ghost-white min-h-100">
          <AuthProvider>
            <div className="max-w-6xl mx-auto p-2">
              <NavbarApp />
              <div className="mt-4 max-w-*">{children}</div>
            </div>
          </AuthProvider>
        </body>
      </html >
    </SessionWrapper>
  );
}
